spring:
  datasource:
    url: jdbc:mysql://localhost:3306/votes?useSSL=false&serverTimezone=UTC
    username: root
    password: slimjay91
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL8Dialect
